postgresql: &postgresql
  adapter: postgresql
  encoding: unicode
  host : localhost
  pool: 5
  timeout: 5000
  username: ands
  password: 12345

development:
  <<: *postgresql
  database: LBD

test:
  <<: *postgresql
  database: LBD

production:
  <<: *postgresql
  database: LBD